version: '3'

services:

  db:
    image: neo4j:latest
    env_file:
      - .env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
        
  web:
    build: ./app/.
    depends_on:
      - db
    env_file:
      - ./app/.env
    ports: 
      - 5000:5000
    links:
      - db:db

volumes:
  db:
  testdb: