version: '3'

services:

  db:
    image: neo4j:latest
    env_file:
      - .env
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - neo4j_ref_net
    volumes:
      - neo4j-referentiel-domains-volume:/data
        
  web:
    build: ./app/.
    depends_on:
      - db
    env_file:
      - ./app/.env
    ports: 
      - 5000:5000
    networks:
      - neo4j_ref_net
    links:
      - db:db

volumes:
  neo4j-referentiel-domains-volume:
    external: true
  
networks:
  neo4j_ref_net:
    driver: bridge